# This is a config for E2B sandbox template.
# You can use template ID (l9dpsr9jnhk86hqbtozt) or template name (rushed-nextjs-template) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("rushed-nextjs-template") # Sync sandbox
# sandbox = await AsyncSandbox.create("rushed-nextjs-template") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('rushed-nextjs-template')

team_id = "c938f40f-0983-4de5-8ee4-ab725967c5e2"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "rushed-nextjs-template"
template_id = "l9dpsr9jnhk86hqbtozt"
